### PR TITLE
feat: laravel 10 compatibility

### PR DESCRIPTION
**Pull request by Quadrubo**
### What
Compatibility with Laravel 10.

### CODE REVIEW

**Comment by Quadrubo** [comment]
I just noticed this doesn't work until the openfoodfacts-php package is updated. I'll still leave this open.

**Comment by d3v4nt** [comment]
guys are you planning on approving this PR?

**Comment by teolemon** [comment]
This just happened @Quadrubo

**Comment by epalmans** [comment]
@Quadrubo thanks for your contribution!

**Pull request merged**
